name: racerider
description: A 2D physics racer built with Flame and Forge2D.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.14.0
  flame_forge2d: ^0.15.0

dependency_overrides:
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
