name: racerider
description: A 2D physics racer built with Flame and Forge2D.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: any
  flame_forge2d: ^0.19.2
  sensors_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
